
import React, { useEffect, useState } from "react";
import "./Deliveryandreturn.css";
import logo from "../../assets/images/crest-large.png";

import axios from "axios";
import { useDispatch, useSelector } from "react-redux";
import { listPrice } from "../../actions/productaction";
import { Translate } from "react-auto-translate";
import { useLayoutEffect } from "react";

export const Deliveryandreturn = () => {
  const [datas, setdatas] = useState(null);
  const dispatch = useDispatch();

  useEffect(async () => {
    const { data } = await axios.get(`http://localhost:5000/api/return`);
    setdatas(data.user[0]);
  }, []);
  const prices = useSelector((state) => state.priceList);
  const { price } = prices;

  useEffect(() => {
    dispatch(listPrice());
  }, [dispatch]);

  useLayoutEffect(() => {
    window.scrollTo(0, 0)
});

  return price == "INR" && datas != null ? (
    <div className="aboutus-container">
      <div className="aboutus-logo">
        <hr />
        <img src={logo} />
        <hr />
      </div>
      <div className="aboutus-head">
        <h1><Translate>{datas.head.INR}</Translate></h1>
      </div>
      <div className="aboutus-container-box">


        <div className="about-us-decor">

          <div>
            <p><Translate>Order Fulfilment Orders are shipped from Monday through Saturday. We pride our selves on shipping your order as fast as possible, Usually within 2 business days after it is placed, Although in some cases we may need upto 5-6 business days to fulfil your order. Holidays and sales may results in longer shipping times, Despite our best efforts to Minimize that. <br/><br/>Occasionally some products will run out of stock due to large orders that come in before inventory is updated, This may result in a delay in shipping just that item or your entire order. we will notify you if this happens. Returns, Exchanges, Replacements, Refunds We absolutely guarantee that the sample or decant of perfume you purchased from makkajperfumes.com is 100% Genuine, Authentic perfume taken from the official manufacturer's bottle and decanted by hand. <br/><br/>Unfortunately, we cannot guarantee that you will like them or not, You may even hate it. Therefore, once you have opened the product and used it, it cannot be returned for a refund or replacements. We carefully wrap all packages so you purchase will arrive safely. <br/><br/>Some time the couriers company's seems to let gorillas into jump up and down on the package. if you get a package and the bottle has broken or leaked, Please snap a photo and email us with ur order number at info@makkaj.com, Upon receipt of the photo, we will send a replacement package for the damaged items. <br/><br/>TERMS & CONDITIONS <br/><br/>This document is an electronic record in terms of Information Technology Act, 2000 & rules thereunder as applicable and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures. <br/><br/>This document is published in accordance with the provisions of Rule 3 (1) of the Information Technology (Intermediaries guidelines) Rules, 2011 that require publishing the rules and regulations, privacy policy and Terms of Use for access or usage of www.makkajperfumes.com Please read the following terms and conditions very carefully as your use of service is subject to your acceptance of and compliance with the following terms and conditions ("Terms"). By subscribing to or using any of our services you agree that you have read, understood and are bound by the Terms, regardless of how you subscribe to or use the services.<br/><br/> If you do not want to be bound by the Terms, you must not subscribe to or use our services. Introduction Welcome to the makkajperfumes.com ("Website" or "makkajperfumes.com") service provided by Makkaj Perfumes Group This website/app/chatbot is owned and operated by Makkaj Group. ('''SSL”). Registered office: Al Umra Industrial Area, Post Box: 20359, Holy Makkah 21955, K.S.A.. <br/><br/>In using the makkajperfumes.com service, of Makkaj Group you are deemed to have accepted the Terms and Conditions of the agreement listed below or as may be revised from time to time, which is, for an indefinite period and you understand and agree that you are bound by such terms till the time you access this website/app/chatbot. If you want to ask us anything about these terms & conditions or have any comments or complaints on or about our website/app/chatbot, please write to us at info@makkaj.com</Translate></p>

          </div>
        </div>


      </div>
    </div>
  ) : datas != null ? (
    <div className="aboutus-container">
      <div className="aboutus-logo">
        <hr />
        <img src={logo} />
        <hr />
      </div>
      <div className="aboutus-head">
        <h1>{datas.head.AED}</h1>
      </div>
      <div className="aboutus-container-box">


        <div className="about-us-decor">

          <div>
            <p>{datas.title.AED}</p>

          </div>
        </div>


      </div>
    </div>
  ) : (<div></div>)
};

